spring:
  application:
    name: guardpay

  profiles:
    active: local   # ?? ?? ????: local

---

spring:
  config:
    activate:
      on-profile: local

  ai:
    openai:
      api-key: dummy   # open ai ??

  datasource:
    url: jdbc:h2:mem:guardpay
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # ??? ??? ??? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  address: 0.0.0.0

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/guardpay?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password:


  jpa:
    hibernate:
      ddl-auto: update   # ?? DB?? update ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://prod-db-server:3306/guardpay?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: validate   # ?? DB? ??? ?? ?? ??
    show-sql: false

server:
  port: 8080
