spring:
  datasource:
    # 1. URL의 'mysql'을 'mariadb'로 변경
    url: jdbc:mariadb://localhost:3306/guardpay?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # 2. MariaDB 드라이버 클래스 이름으로 변경
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:  # 여기에 실제 비밀번호를 입력하세요

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 3. Hibernate Dialect(방언)를 MariaDB에 맞게 변경
    database-platform: org.hibernate.dialect.MariaDBDialect